### ISSUE TITLE
Is this implementation outdated?

### ISSUE THREAD

**Issue by afshawnlotfi** [mozilla/node-srp#39]
I understand this repo may not be maintained as it has not been updated since 2015, however was wondering security-wise if the SRP standard implementation has changed since then. I see that this is version SRP-6a which appears to be the latest on http://srp.stanford.edu/design.html, just wondering though.

**Comment by warner** [comment]
SRP-6a is the latest that I was aware of, but I stopped really paying attention to SRP several years ago, in favor of SPAKE2, which is a lot cleaner and has a solid security proof.

* http://www.di.ens.fr/~pointche/Documents/Papers/2005_rsa.pdf

I've got implementations in [Python](https://github.com/warner/python-spake2) and [Rust](https://github.com/warner/spake2.rs), and I know of an implementation in [Go](https://salsa.debian.org/vasudev/gospake2). For Javascript, there's a [PR to SJCL](https://github.com/bitwiseshiftleft/sjcl/pull/273) that would add SPAKE2 support, but SJCL hasn't seen a lot of activity in the last few years so I'm not sure it will ever get landed (however SJCL is definitely worth a look, as crypto tools on JS go).

hope that helps!
 -Brian
